# Generated by Django 4.2.11 on 2024-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(blank=True, max_length=60, null=True)),
                ('precio', models.FloatField(null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('disponibilidad', models.BooleanField(default=False)),
            ],
        ),
    ]
